In [1]:
import numpy as np
a = np.array([1,2,3,4])
print (a)

[1 2 3 4]


In [16]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)
print np.shape(a)

tic1 = time.time()
c = np.dot(a,b)
toc1 = time.time()
print("C = "+str(c))
print("Vectorized version:"+str(1000*(toc1-tic1))+"ms")

c=0
tic2 = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc2 = time.time()
print("C = "+str(c))
print("For loop version:"+str(1000*(toc2-tic2))+"ms")

speedup= (toc2-tic2)/(toc1-tic1)
print("Speedup:"+ str(speedup))


(1000000L,)
C = 249879.457775
Vectorized version:2.00009346008ms
C = 249879.457775
For loop version:893.999814987ms
Speedup:446.979020145


In [22]:
A = np.array([[56,0,4.4,68],[1.2,104,52,8],[1.8,135,99,0.9]])
print(A)
cal = A.sum(axis=0)
print(cal)
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]
[  59.   239.   155.4   76.9]
[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [33]:
a = np.random.randn(5)
print(a)
print(a.shape)
# note this is a rank 1 vector and is neither a row nor a column vector
# if you print a.T, it will look the same as a!
print(a.T)
# the solution is to specifically set the dimensions of a, when initializing
a = np.random.randn(5,1)
# also note, you will see two square brackets now instead of one when it was a rank 1 vector
print(a)
print(a.shape)
print(a.T)
assert(a.shape == (5,1))
a = a.reshape((5,1))

[ 0.21548536  0.07608122  0.49536866  0.20535     0.75513931]
(5L,)
[ 0.21548536  0.07608122  0.49536866  0.20535     0.75513931]
[[-0.06547018]
 [-2.51658328]
 [-1.23646758]
 [ 0.79959063]
 [-0.4414066 ]]
(5L, 1L)
[[-0.06547018 -2.51658328 -1.23646758  0.79959063 -0.4414066 ]]
